import { z } from 'zod';

const CargoTypeSchema = z.object({
  id: z.string(),
  name: z.string(),
  basePrice: z.number(),
  weight: z.number(),       // per unit
  origins: z.array(z.string()),      // port IDs where produced
  destinations: z.array(z.string()), // port IDs where demanded
  heatLevel: z.number(),    // 0-100: how suspicious when found
  perishable: z.boolean(),
  legal: z.boolean(),
  category: z.enum(['commodity', 'luxury', 'military', 'contraband', 'provision']),
});

export type CargoType = z.infer<typeof CargoTypeSchema>;

export const CARGO_TYPES: Record<string, CargoType> = {
  sugar: {
    id: 'sugar',
    name: 'Sugar',
    basePrice: 20,
    weight: 1,
    origins: ['port_royal', 'havana', 'santo_domingo', 'bridgetown', 'basseterre', 'petit_goave'],
    destinations: ['boston', 'charles_town', 'london', 'seville_cadiz', 'amsterdam'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'commodity',
  },
  rum: {
    id: 'rum',
    name: 'Rum',
    basePrice: 35,
    weight: 1,
    origins: ['port_royal', 'bridgetown', 'nassau', 'basseterre', 'petit_goave'],
    destinations: ['boston', 'charles_town', 'cartagena', 'london', 'cape_coast_castle'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'commodity',
  },
  tobacco: {
    id: 'tobacco',
    name: 'Tobacco',
    basePrice: 25,
    weight: 1,
    origins: ['havana', 'charles_town', 'santo_domingo'],
    destinations: ['london', 'amsterdam', 'boston', 'bridgetown', 'seville_cadiz'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'commodity',
  },
  cotton: {
    id: 'cotton',
    name: 'Cotton',
    basePrice: 15,
    weight: 1,
    origins: ['charles_town', 'cartagena', 'bridgetown'],
    destinations: ['london', 'amsterdam', 'boston'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'commodity',
  },
  rice: {
    id: 'rice',
    name: 'Rice',
    basePrice: 12,
    weight: 1.5,
    origins: ['charles_town'],
    destinations: ['london', 'boston', 'bridgetown', 'port_royal'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'commodity',
  },
  indigo: {
    id: 'indigo',
    name: 'Indigo',
    basePrice: 60,
    weight: 0.5,
    origins: ['santo_domingo', 'cartagena', 'charles_town'],
    destinations: ['london', 'amsterdam', 'boston'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'luxury',
  },
  cacao: {
    id: 'cacao',
    name: 'Cacao',
    basePrice: 40,
    weight: 1,
    origins: ['cartagena', 'veracruz', 'portobelo'],
    destinations: ['london', 'amsterdam', 'seville_cadiz', 'havana'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'commodity',
  },
  logwood: {
    id: 'logwood',
    name: 'Logwood',
    basePrice: 30,
    weight: 2,
    origins: ['portobelo', 'petit_goave'],
    destinations: ['london', 'amsterdam', 'boston'],
    heatLevel: 10,
    perishable: false,
    legal: true,
    category: 'commodity',
  },
  naval_stores: {
    id: 'naval_stores',
    name: 'Naval Stores',
    basePrice: 18,
    weight: 2,
    origins: ['charles_town', 'boston'],
    destinations: ['port_royal', 'bridgetown', 'london', 'nassau'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'commodity',
  },
  cochineal: {
    id: 'cochineal',
    name: 'Cochineal',
    basePrice: 90,
    weight: 0.2,
    origins: ['veracruz', 'portobelo'],
    destinations: ['london', 'amsterdam', 'seville_cadiz'],
    heatLevel: 10,
    perishable: false,
    legal: true,
    category: 'luxury',
  },
  spices: {
    id: 'spices',
    name: 'Spices',
    basePrice: 80,
    weight: 0.3,
    origins: ['cartagena', 'portobelo', 'veracruz'],
    destinations: ['london', 'amsterdam', 'boston', 'havana'],
    heatLevel: 10,
    perishable: false,
    legal: true,
    category: 'luxury',
  },
  silk: {
    id: 'silk',
    name: 'Silk',
    basePrice: 120,
    weight: 0.2,
    origins: ['veracruz', 'cartagena', 'portobelo'],
    destinations: ['london', 'seville_cadiz', 'havana', 'charles_town'],
    heatLevel: 15,
    perishable: false,
    legal: true,
    category: 'luxury',
  },
  gold: {
    id: 'gold',
    name: 'Gold',
    basePrice: 500,
    weight: 2,
    origins: ['portobelo', 'cartagena', 'veracruz'],
    destinations: ['seville_cadiz', 'london', 'havana', 'nassau'],
    heatLevel: 60,
    perishable: false,
    legal: true,
    category: 'luxury',
  },
  silver: {
    id: 'silver',
    name: 'Silver',
    basePrice: 200,
    weight: 3,
    origins: ['portobelo', 'cartagena', 'veracruz'],
    destinations: ['seville_cadiz', 'london', 'havana'],
    heatLevel: 50,
    perishable: false,
    legal: true,
    category: 'luxury',
  },
  gunpowder: {
    id: 'gunpowder',
    name: 'Gunpowder',
    basePrice: 45,
    weight: 1.5,
    origins: ['london', 'amsterdam', 'boston'],
    destinations: ['port_royal', 'nassau', 'havana', 'cartagena', 'charles_town'],
    heatLevel: 30,
    perishable: false,
    legal: true,
    category: 'military',
  },
  cannons: {
    id: 'cannons',
    name: 'Cannons',
    basePrice: 150,
    weight: 5,
    origins: ['london', 'amsterdam', 'boston'],
    destinations: ['port_royal', 'nassau', 'cartagena', 'havana'],
    heatLevel: 40,
    perishable: false,
    legal: true,
    category: 'military',
  },
  slaves: {
    id: 'slaves',
    name: 'Enslaved People',
    basePrice: 100,
    weight: 2,
    origins: ['cape_coast_castle', 'elmina', 'whydah'],
    destinations: ['port_royal', 'bridgetown', 'charles_town', 'havana', 'cartagena', 'willemstad', 'santo_domingo'],
    heatLevel: 5,
    perishable: false,
    legal: true,
    category: 'commodity',
  },
  medicine: {
    id: 'medicine',
    name: 'Medicine',
    basePrice: 70,
    weight: 0.5,
    origins: ['london', 'amsterdam', 'boston'],
    destinations: ['port_royal', 'nassau', 'havana', 'bridgetown', 'portobelo', 'charles_town'],
    heatLevel: 0,
    perishable: true,
    legal: true,
    category: 'provision',
  },
  provisions: {
    id: 'provisions',
    name: 'Ship Provisions',
    basePrice: 10,
    weight: 1,
    origins: ['boston', 'charles_town', 'havana', 'bridgetown', 'willemstad'],
    destinations: ['nassau', 'port_royal', 'tortuga', 'petit_goave', 'portobelo'],
    heatLevel: 0,
    perishable: true,
    legal: true,
    category: 'provision',
  },
  stolen_goods: {
    id: 'stolen_goods',
    name: 'Stolen Goods',
    basePrice: 40,
    weight: 1,
    origins: [],
    destinations: ['nassau', 'tortuga', 'petit_goave', 'port_royal', 'willemstad'],
    heatLevel: 80,
    perishable: false,
    legal: false,
    category: 'contraband',
  },

  // ── New organic/agricultural cargo types ─────────────────

  pimento: {
    id: 'pimento',
    name: 'Pimento (Allspice)',
    basePrice: 65,
    weight: 0.3,
    origins: ['port_royal'],
    destinations: ['london', 'amsterdam', 'boston', 'seville_cadiz'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'luxury',
  },
  ginger: {
    id: 'ginger',
    name: 'Ginger',
    basePrice: 50,
    weight: 0.5,
    origins: ['port_royal', 'bridgetown'],
    destinations: ['london', 'amsterdam', 'boston', 'seville_cadiz'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'luxury',
  },
  timber: {
    id: 'timber',
    name: 'Tropical Timber',
    basePrice: 40,
    weight: 4,
    origins: ['port_royal', 'havana', 'santo_domingo'],
    destinations: ['london', 'amsterdam', 'boston', 'seville_cadiz'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'commodity',
  },
  hides: {
    id: 'hides',
    name: 'Cattle Hides',
    basePrice: 18,
    weight: 2,
    origins: ['havana', 'santo_domingo', 'cartagena', 'charles_town'],
    destinations: ['london', 'amsterdam', 'seville_cadiz', 'boston'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'commodity',
  },
  salt: {
    id: 'salt',
    name: 'Salt',
    basePrice: 8,
    weight: 2,
    origins: ['willemstad'],
    destinations: ['boston', 'charles_town', 'port_royal', 'bridgetown', 'nassau'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'provision',
  },
  dried_fish: {
    id: 'dried_fish',
    name: 'Salt Cod & Dried Fish',
    basePrice: 12,
    weight: 1,
    origins: ['boston'],
    destinations: ['port_royal', 'bridgetown', 'nassau', 'basseterre', 'havana', 'cartagena'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'provision',
  },
  citrus: {
    id: 'citrus',
    name: 'Citrus Fruit (Limes & Oranges)',
    basePrice: 15,
    weight: 1,
    origins: ['havana', 'port_royal', 'bridgetown', 'seville_cadiz'],
    destinations: ['boston', 'london', 'amsterdam', 'nassau'],
    heatLevel: 0,
    perishable: true,
    legal: true,
    category: 'provision',
  },
  wine: {
    id: 'wine',
    name: 'Wine & Spirits',
    basePrice: 30,
    weight: 1.5,
    origins: ['seville_cadiz', 'london', 'amsterdam'],
    destinations: ['havana', 'cartagena', 'port_royal', 'bridgetown', 'charles_town', 'boston', 'nassau', 'portobelo'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'luxury',
  },
  flour: {
    id: 'flour',
    name: 'Flour & Grain',
    basePrice: 14,
    weight: 1.5,
    origins: ['boston', 'charles_town', 'london', 'seville_cadiz', 'amsterdam'],
    destinations: ['port_royal', 'bridgetown', 'nassau', 'havana', 'basseterre', 'tortuga', 'petit_goave'],
    heatLevel: 0,
    perishable: true,
    legal: true,
    category: 'provision',
  },
  palm_oil: {
    id: 'palm_oil',
    name: 'Palm Oil',
    basePrice: 22,
    weight: 1.5,
    origins: ['cape_coast_castle', 'elmina', 'whydah'],
    destinations: ['london', 'amsterdam', 'seville_cadiz'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'commodity',
  },
  vanilla: {
    id: 'vanilla',
    name: 'Vanilla',
    basePrice: 200,
    weight: 0.1,
    origins: ['veracruz'],
    destinations: ['seville_cadiz', 'london', 'amsterdam'],
    heatLevel: 15,
    perishable: false,
    legal: true,
    category: 'luxury',
  },
  annatto: {
    id: 'annatto',
    name: 'Annatto (Achiote Dye)',
    basePrice: 25,
    weight: 0.5,
    origins: ['port_royal', 'havana', 'cartagena', 'veracruz', 'bridgetown', 'santo_domingo', 'petit_goave'],
    destinations: ['london', 'amsterdam', 'seville_cadiz', 'boston'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'commodity',
  },

  // ── Precious gems ────────────────────────────────────────

  emeralds: {
    id: 'emeralds',
    name: 'Emeralds',
    basePrice: 800,
    weight: 0.05,
    origins: ['cartagena'],
    destinations: ['seville_cadiz', 'london', 'amsterdam'],
    heatLevel: 70,
    perishable: false,
    legal: true,
    category: 'luxury',
  },
  pearls: {
    id: 'pearls',
    name: 'Pearls',
    basePrice: 350,
    weight: 0.05,
    origins: ['cartagena'],                // Margarita pearls shipped via Cartagena
    destinations: ['seville_cadiz', 'london', 'amsterdam', 'havana'],
    heatLevel: 50,
    perishable: false,
    legal: true,
    category: 'luxury',
  },

  // ── Animal products ──────────────────────────────────────

  ivory: {
    id: 'ivory',
    name: 'Ivory',
    basePrice: 120,
    weight: 3,
    origins: ['cape_coast_castle', 'elmina', 'whydah'],
    destinations: ['london', 'amsterdam', 'seville_cadiz'],
    heatLevel: 10,
    perishable: false,
    legal: true,
    category: 'luxury',
  },
  whale_products: {
    id: 'whale_products',
    name: 'Whale Oil, Spermaceti & Baleen',
    basePrice: 55,
    weight: 2,
    origins: ['boston'],
    destinations: ['london', 'amsterdam', 'port_royal', 'bridgetown', 'charles_town'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'commodity',
  },
  ambergris: {
    id: 'ambergris',
    name: 'Ambergris',
    basePrice: 600,
    weight: 0.1,
    origins: ['nassau', 'port_royal', 'boston'],
    destinations: ['london', 'amsterdam', 'seville_cadiz'],
    heatLevel: 30,
    perishable: false,
    legal: true,
    category: 'luxury',
  },
  turtle: {
    id: 'turtle',
    name: 'Live Turtle',
    basePrice: 8,
    weight: 3,
    origins: ['port_royal', 'nassau'],
    destinations: ['port_royal', 'havana', 'nassau', 'charles_town', 'bridgetown', 'boston'],
    heatLevel: 0,
    perishable: true,
    legal: true,
    category: 'provision',
  },
  tortoiseshell: {
    id: 'tortoiseshell',
    name: 'Tortoiseshell',
    basePrice: 150,
    weight: 0.3,
    origins: ['port_royal', 'nassau'],
    destinations: ['london', 'amsterdam', 'seville_cadiz', 'boston'],
    heatLevel: 5,
    perishable: false,
    legal: true,
    category: 'luxury',
  },

  // ── Specialty timber (split from generic) ────────────────

  mahogany: {
    id: 'mahogany',
    name: 'Mahogany',
    basePrice: 80,
    weight: 4,
    origins: ['port_royal', 'havana', 'santo_domingo'],
    destinations: ['london', 'amsterdam', 'boston', 'seville_cadiz'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'luxury',
  },
  lignum_vitae: {
    id: 'lignum_vitae',
    name: 'Lignum Vitae',
    basePrice: 100,
    weight: 5,
    origins: ['port_royal'],
    destinations: ['london', 'amsterdam', 'boston'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'commodity',
  },
  kola_nuts: {
    id: 'kola_nuts',
    name: 'Kola Nuts',
    basePrice: 15,
    weight: 0.5,
    origins: ['cape_coast_castle', 'elmina', 'whydah'],
    destinations: ['cape_coast_castle', 'elmina', 'whydah'],  // African regional trade
    heatLevel: 0,
    perishable: true,
    legal: true,
    category: 'commodity',
  },

  // ── Manufactured trade goods ─────────────────────────────
  // The other legs of the triangular trade

  textiles: {
    id: 'textiles',
    name: 'Cloth & Textiles',
    basePrice: 35,
    weight: 1,
    origins: ['london', 'amsterdam', 'seville_cadiz'],
    destinations: ['cape_coast_castle', 'elmina', 'whydah', 'port_royal', 'bridgetown', 'havana', 'cartagena', 'nassau'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'commodity',
  },
  iron_bars: {
    id: 'iron_bars',
    name: 'Iron Bars',
    basePrice: 20,
    weight: 4,
    origins: ['london', 'amsterdam', 'seville_cadiz'],
    destinations: ['cape_coast_castle', 'elmina', 'whydah', 'port_royal', 'havana', 'cartagena', 'boston'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'commodity',
  },
  trade_beads: {
    id: 'trade_beads',
    name: 'Glass Beads & Cowrie Shells',
    basePrice: 5,
    weight: 0.5,
    origins: ['amsterdam', 'london', 'seville_cadiz'],
    destinations: ['cape_coast_castle', 'elmina', 'whydah'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'commodity',
  },
  muskets: {
    id: 'muskets',
    name: 'Muskets & Small Arms',
    basePrice: 80,
    weight: 2,
    origins: ['london', 'amsterdam', 'seville_cadiz'],
    destinations: ['cape_coast_castle', 'elmina', 'whydah', 'nassau', 'port_royal', 'havana', 'cartagena'],
    heatLevel: 45,
    perishable: false,
    legal: true,
    category: 'military',
  },

  // ── Processed goods (secondary products) ─────────────────

  molasses: {
    id: 'molasses',
    name: 'Molasses',
    basePrice: 8,
    weight: 1.5,
    origins: ['port_royal', 'bridgetown', 'basseterre', 'havana', 'santo_domingo', 'petit_goave'],
    destinations: ['boston', 'charles_town', 'london', 'nassau'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'commodity',
  },
  chocolate: {
    id: 'chocolate',
    name: 'Chocolate (Processed Cacao)',
    basePrice: 70,
    weight: 0.5,
    origins: ['veracruz', 'cartagena', 'havana'],
    destinations: ['seville_cadiz', 'london', 'amsterdam', 'boston'],
    heatLevel: 10,
    perishable: false,
    legal: true,
    category: 'luxury',
  },
  refined_sugar: {
    id: 'refined_sugar',
    name: 'Refined White Sugar',
    basePrice: 45,
    weight: 1,
    origins: ['amsterdam', 'london'],       // refined in European refineries
    destinations: ['boston', 'charles_town', 'port_royal', 'seville_cadiz'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'luxury',
  },
  cured_tobacco: {
    id: 'cured_tobacco',
    name: 'Cured Tobacco (Havana Leaf)',
    basePrice: 40,
    weight: 0.8,
    origins: ['havana'],                     // premium cured product
    destinations: ['seville_cadiz', 'london', 'amsterdam', 'boston', 'port_royal'],
    heatLevel: 5,
    perishable: false,
    legal: true,
    category: 'luxury',
  },
  leather: {
    id: 'leather',
    name: 'Tanned Leather',
    basePrice: 30,
    weight: 1.5,
    origins: ['havana', 'santo_domingo', 'cartagena', 'seville_cadiz', 'london'],
    destinations: ['port_royal', 'bridgetown', 'boston', 'london', 'amsterdam'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'commodity',
  },

  // ── Ship supplies (essential, always on board) ───────────

  cordage: {
    id: 'cordage',
    name: 'Rope & Cordage',
    basePrice: 16,
    weight: 2,
    origins: ['london', 'amsterdam', 'boston'],
    destinations: ['port_royal', 'bridgetown', 'havana', 'nassau', 'cartagena', 'charles_town'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'commodity',
  },
  sailcloth: {
    id: 'sailcloth',
    name: 'Sailcloth & Canvas',
    basePrice: 22,
    weight: 1.5,
    origins: ['london', 'amsterdam'],
    destinations: ['port_royal', 'bridgetown', 'havana', 'nassau', 'boston', 'cartagena', 'charles_town'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'commodity',
  },
  ship_hardware: {
    id: 'ship_hardware',
    name: 'Nails, Bolts & Ship Fittings',
    basePrice: 25,
    weight: 3,
    origins: ['london', 'amsterdam', 'boston'],
    destinations: ['port_royal', 'bridgetown', 'havana', 'nassau', 'cartagena', 'charles_town'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'commodity',
  },
  salt_meat: {
    id: 'salt_meat',
    name: 'Salt Beef & Pork',
    basePrice: 12,
    weight: 1.5,
    origins: ['boston', 'charles_town', 'london', 'havana'],
    destinations: ['port_royal', 'bridgetown', 'nassau', 'basseterre', 'tortuga', 'petit_goave'],
    heatLevel: 0,
    perishable: false,
    legal: true,
    category: 'provision',
  },

  // ── Plunder valuables (found on persons, in cabins, shore raids) ──

  coins: {
    id: 'coins',
    name: 'Coins & Pieces of Eight',
    basePrice: 1,                            // 1 coin = 1 unit of currency (peso/piece of eight)
    weight: 0.02,
    origins: ['veracruz', 'portobelo', 'cartagena', 'havana', 'seville_cadiz'],
    destinations: ['nassau', 'port_royal', 'tortuga', 'london', 'amsterdam'],
    heatLevel: 40,
    perishable: false,
    legal: true,
    category: 'luxury',
  },
  plate: {
    id: 'plate',
    name: 'Silverware, Church Plate & Personal Valuables',
    basePrice: 250,
    weight: 1,
    origins: ['havana', 'cartagena', 'portobelo', 'veracruz', 'santo_domingo', 'seville_cadiz'],
    destinations: ['nassau', 'tortuga', 'port_royal', 'london', 'amsterdam'],
    heatLevel: 75,
    perishable: false,
    legal: true,
    category: 'luxury',
  },
  jewelry: {
    id: 'jewelry',
    name: 'Jewelry & Precious Stones',
    basePrice: 400,
    weight: 0.05,
    origins: ['cartagena', 'havana', 'veracruz', 'seville_cadiz', 'london', 'amsterdam'],
    destinations: ['nassau', 'tortuga', 'port_royal', 'london', 'amsterdam', 'seville_cadiz'],
    heatLevel: 70,
    perishable: false,
    legal: true,
    category: 'luxury',
  },
  charts: {
    id: 'charts',
    name: 'Navigation Charts & Instruments',
    basePrice: 100,
    weight: 0.2,
    origins: ['london', 'amsterdam', 'seville_cadiz'],
    destinations: ['nassau', 'port_royal', 'boston', 'havana'],
    heatLevel: 20,
    perishable: false,
    legal: true,
    category: 'commodity',
  },
};
