import { z } from 'zod';

// ============================================================
// Port harbor approach details
// ============================================================

const HarborApproachSchema = z.object({
  entranceWidth: z.number().optional(),   // meters
  entranceDepth: z.number().optional(),   // meters
  maxDraft: z.number().optional(),        // meters - max ship draft that can enter
  tidalRange: z.number(),                 // meters
  anchorageCapacity: z.number(),          // number of ships
  approachDirections: z.array(z.string()),
  defenses: z.string(),
  notes: z.string().optional(),
});

export type HarborApproach = z.infer<typeof HarborApproachSchema>;

// ============================================================
// Port profile
// ============================================================

const PortProfileSchema = z.object({
  id: z.string(),
  name: z.string(),
  seaZoneId: z.string(),           // sea zone this port is accessible from
  controller: z.string(),
  corruption: z.number(),
  prosperity: z.number(),
  population: z.number(),
  fortStrength: z.number(),
  diseaseProfile: z.object({
    malaria: z.number(),
    yellowFever: z.number(),
    scurvy: z.number(),
    dysentery: z.number(),
  }),
  tavernQuality: z.number(),
  shipyardQuality: z.number(),
  marketSize: z.number(),
  pirateFriendly: z.boolean(),
  latitude: z.number(),
  longitude: z.number(),
  description: z.string(),
  harbor: HarborApproachSchema,
  terrain: z.string(),
  portType: z.enum(['major_port', 'minor_port', 'trading_post', 'european_city', 'pirate_hideout']),
});

export type PortProfile = z.infer<typeof PortProfileSchema>;

// ============================================================
// 14 Caribbean Ports
// ============================================================

export const PORT_PROFILES: Record<string, PortProfile> = {
  nassau: {
    id: 'nassau',
    name: 'Nassau',
    seaZoneId: 'great_bahama_bank',
    controller: 'pirate_republic',
    corruption: 95,
    prosperity: 40,
    population: 1100,
    fortStrength: 20,
    diseaseProfile: { malaria: 30, yellowFever: 20, scurvy: 10, dysentery: 25 },
    tavernQuality: 80,
    shipyardQuality: 40,
    marketSize: 30,
    pirateFriendly: true,
    latitude: 25.06,
    longitude: -77.35,
    description: 'The Pirate Republic. Lawless haven where buccaneers rule and the King\'s law means nothing.',
    harbor: {
      entranceWidth: undefined,
      entranceDepth: 3.7, // ~12 feet max draft
      maxDraft: 3.7,
      tidalRange: 0.9, // ~3 feet
      anchorageCapacity: 500,
      approachDirections: ['west', 'east'],
      defenses: 'Fort Nassau covers the western entrance. The shallow bar IS the primary defense — ships over 500 tons cannot enter.',
      notes: 'Eastern entrance even shallower — only small boats. Hog Island forms natural breakwater.',
    },
    terrain: 'Low scrubland, sandy soil, coral rock. Dense bush interior with hiding spots. Freshwater wells (limited). Harbor shallow enough that large warships cannot enter.',
    portType: 'major_port',
  },

  port_royal: {
    id: 'port_royal',
    name: 'Port Royal',
    seaZoneId: 'kingston_approaches',
    controller: 'england',
    corruption: 60,
    prosperity: 75,
    population: 2000,
    fortStrength: 70,
    diseaseProfile: { malaria: 40, yellowFever: 35, scurvy: 5, dysentery: 20 },
    tavernQuality: 90,
    shipyardQuality: 70,
    marketSize: 80,
    pirateFriendly: false,
    latitude: 17.93,
    longitude: -76.84,
    description: 'Once the wickedest city on Earth. Now under Crown control but still rife with corruption.',
    harbor: {
      entranceWidth: undefined,
      entranceDepth: 15,
      maxDraft: 12,
      tidalRange: 0.3, // ~1 foot
      anchorageCapacity: 200,
      approachDirections: ['south', 'southeast'],
      defenses: 'Fort Charles commands the approach. Fort Rupert and Fort Walker provide crossfire. Morgan\'s Line connects defenses across the Palisadoes.',
      notes: 'One of the largest natural harbors in the world. Deep water close to shore — large warships can dock directly.',
    },
    terrain: 'Palisadoes sand spit connecting to mainland. Kingston across the harbor. Blue Mountains visible inland — Maroon territory.',
    portType: 'major_port',
  },

  havana: {
    id: 'havana',
    name: 'Havana',
    seaZoneId: 'havana_roads',
    controller: 'spain',
    corruption: 45,
    prosperity: 85,
    population: 12000,
    fortStrength: 95,
    diseaseProfile: { malaria: 35, yellowFever: 40, scurvy: 5, dysentery: 15 },
    tavernQuality: 70,
    shipyardQuality: 80,
    marketSize: 90,
    pirateFriendly: false,
    latitude: 23.13,
    longitude: -82.38,
    description: 'Jewel of the Spanish Caribbean. Heavily fortified staging point for treasure fleets.',
    harbor: {
      entranceWidth: 200, // 180-220m
      entranceDepth: 12.8,
      maxDraft: 10,
      tidalRange: 0.3, // ~1 foot
      anchorageCapacity: 100,
      approachDirections: ['north'],
      defenses: 'Ships must pass within point-blank range of BOTH El Morro (64 guns) and La Punta simultaneously. Heavy chain strung between them at night physically blocks entry.',
      notes: 'Narrow 800m channel. During treasure fleet assembly, 30-50 ships crowd the harbor.',
    },
    terrain: 'Flat agricultural land (tobacco, sugar) extending inland. Harbor entrance narrow and defensible.',
    portType: 'major_port',
  },

  tortuga: {
    id: 'tortuga',
    name: 'Tortuga',
    seaZoneId: 'tortuga_waters',
    controller: 'france',
    corruption: 85,
    prosperity: 30,
    population: 750,
    fortStrength: 25,
    diseaseProfile: { malaria: 45, yellowFever: 30, scurvy: 15, dysentery: 30 },
    tavernQuality: 75,
    shipyardQuality: 35,
    marketSize: 25,
    pirateFriendly: true,
    latitude: 20.06,
    longitude: -72.78,
    description: 'The original buccaneer haven. Past its glory days but corsair sympathies remain. Nassau has replaced it as the primary pirate haven.',
    harbor: {
      entranceWidth: undefined,
      entranceDepth: 4,
      maxDraft: 4,
      tidalRange: 0.3,
      anchorageCapacity: 30,
      approachDirections: ['south'],
      defenses: 'Fort de Rocher overlooks Cayona harbor from a rocky cliff. 24 guns, partially ruined.',
    },
    terrain: 'Rugged mountain interior, forested, hiding places. Northern coast uninhabited, rocky, dangerous currents. Fresh water streams.',
    portType: 'minor_port',
  },

  bridgetown: {
    id: 'bridgetown',
    name: 'Bridgetown',
    seaZoneId: 'windward_islands_waters',
    controller: 'england',
    corruption: 35,
    prosperity: 70,
    population: 5500,
    fortStrength: 55,
    diseaseProfile: { malaria: 25, yellowFever: 20, scurvy: 5, dysentery: 15 },
    tavernQuality: 60,
    shipyardQuality: 60,
    marketSize: 65,
    pirateFriendly: false,
    latitude: 13.10,
    longitude: -59.62,
    description: 'Prosperous English sugar colony. First Caribbean port of call from the Atlantic crossing.',
    harbor: {
      entranceWidth: undefined,
      entranceDepth: 10,
      maxDraft: 8,
      tidalRange: 0.75, // 2-3 feet
      anchorageCapacity: 80,
      approachDirections: ['west', 'southwest'],
      defenses: 'Three forts (James, Willoughby, Charles) cover Carlisle Bay. The Garrison at Needham\'s Point.',
      notes: 'Open bay, not enclosed harbor. Vulnerable to weather from west/southwest.',
    },
    terrain: 'Sugar plantations blanket the interior — almost entirely deforested. Mount Hillaby visible from sea. No significant wilderness.',
    portType: 'major_port',
  },

  charles_town: {
    id: 'charles_town',
    name: 'Charles Town',
    seaZoneId: 'carolina_shelf',
    controller: 'england',
    corruption: 40,
    prosperity: 65,
    population: 4500,
    fortStrength: 45,
    diseaseProfile: { malaria: 30, yellowFever: 15, scurvy: 5, dysentery: 20 },
    tavernQuality: 55,
    shipyardQuality: 55,
    marketSize: 60,
    pirateFriendly: false,
    latitude: 32.78,
    longitude: -79.93,
    description: 'The only walled English colonial city in North America. Rice and naval stores trade. Blackbeard blockaded it in 1718.',
    harbor: {
      entranceWidth: undefined,
      entranceDepth: 6,
      maxDraft: 5,
      tidalRange: 1.7, // 5-6 feet
      anchorageCapacity: 60,
      approachDirections: ['southeast'],
      defenses: 'Fort Johnson on James Island. Half Moon Battery on the waterfront. Sand bars require local pilot.',
      notes: 'Large harbor at confluence of Ashley and Cooper Rivers. Sand bars at entrance — ships must wait for high tide.',
    },
    terrain: 'Low Country — flat, swampy, rice paddies. Sea Islands with plantations. Dense coastal forest and marsh.',
    portType: 'major_port',
  },

  santo_domingo: {
    id: 'santo_domingo',
    name: 'Santo Domingo',
    seaZoneId: 'tortuga_waters',
    controller: 'spain',
    corruption: 50,
    prosperity: 60,
    population: 8000,
    fortStrength: 65,
    diseaseProfile: { malaria: 40, yellowFever: 35, scurvy: 5, dysentery: 25 },
    tavernQuality: 50,
    shipyardQuality: 55,
    marketSize: 55,
    pirateFriendly: false,
    latitude: 18.47,
    longitude: -69.90,
    description: 'Oldest European settlement in the Americas. Walled city with active Spanish patrols.',
    harbor: {
      entranceWidth: undefined,
      entranceDepth: 6,
      maxDraft: 5,
      tidalRange: 0.3,
      anchorageCapacity: 40,
      approachDirections: ['south'],
      defenses: 'Fortaleza Ozama — oldest European military construction in the Americas. Tower and walls at river mouth command the harbor entrance. Extensive city walls.',
    },
    terrain: 'Ozama River navigable upriver. Sugar and cattle country inland. Cordillera Central mountains distant but visible.',
    portType: 'major_port',
  },

  cartagena: {
    id: 'cartagena',
    name: 'Cartagena de Indias',
    seaZoneId: 'spanish_main_coast',
    controller: 'spain',
    corruption: 30,
    prosperity: 90,
    population: 15000,
    fortStrength: 95,
    diseaseProfile: { malaria: 50, yellowFever: 45, scurvy: 5, dysentery: 20 },
    tavernQuality: 65,
    shipyardQuality: 75,
    marketSize: 85,
    pirateFriendly: false,
    latitude: 10.39,
    longitude: -75.51,
    description: 'The most fortified city in the Americas. Treasure fleet assembly point. Nearly impregnable.',
    harbor: {
      entranceWidth: undefined,
      entranceDepth: 12,
      maxDraft: 10,
      tidalRange: 0.3,
      anchorageCapacity: 100,
      approachDirections: ['southwest'],
      defenses: 'Bocachica is the ONLY usable entrance — narrow, defended by forts San Fernando, San José, Santa Bárbara. Castillo San Felipe de Barajas dominates all approaches. 11km of massive city walls, 23 bastions.',
      notes: 'Bocagrande silted up. Ships must run a gauntlet of 4+ forts through narrow Bocachica channel.',
    },
    terrain: 'Coastal lowlands. Three distinct districts: San Pedro (elite), San Diego (merchants), Getsemaní (workers).',
    portType: 'major_port',
  },

  portobelo: {
    id: 'portobelo',
    name: 'Portobelo',
    seaZoneId: 'darien_coast',
    controller: 'spain',
    corruption: 55,
    prosperity: 80,
    population: 300,
    fortStrength: 50,
    diseaseProfile: { malaria: 60, yellowFever: 50, scurvy: 5, dysentery: 35 },
    tavernQuality: 45,
    shipyardQuality: 40,
    marketSize: 70,
    pirateFriendly: false,
    latitude: 9.55,
    longitude: -79.65,
    description: 'Terminus of the Spanish treasure route from Peru. Population swells to 5,000+ during the treasure fair.',
    harbor: {
      entranceWidth: undefined,
      entranceDepth: 15,
      maxDraft: 10,
      tidalRange: 0.5,
      anchorageCapacity: 40,
      approachDirections: ['north'],
      defenses: '10 forts total. Fuerte San Felipe de Todo Fierro (main), Fuerte Santiago, Fuerte San Jerónimo, plus 7 additional batteries on surrounding hills.',
      notes: 'Deep natural harbor surrounded by hills. Excellent shelter, terrible climate (swamp).',
    },
    terrain: 'Swamp, dense jungle, extreme humidity. One of the most unhealthy places in the Spanish Empire. Jungle effectively impenetrable off the road.',
    portType: 'major_port',
  },

  boston: {
    id: 'boston',
    name: 'Boston',
    seaZoneId: 'boston_waters',
    controller: 'england',
    corruption: 20,
    prosperity: 60,
    population: 8000,
    fortStrength: 50,
    diseaseProfile: { malaria: 10, yellowFever: 5, scurvy: 10, dysentery: 10 },
    tavernQuality: 50,
    shipyardQuality: 70,
    marketSize: 55,
    pirateFriendly: false,
    latitude: 42.36,
    longitude: -71.06,
    description: 'Puritan port with strict law. Best shipyards in the English colonies. Pirates hang here.',
    harbor: {
      entranceWidth: undefined,
      entranceDepth: 12,
      maxDraft: 10,
      tidalRange: 2.75, // 9-10 feet — largest tidal range in the game
      anchorageCapacity: 100,
      approachDirections: ['east', 'northeast'],
      defenses: 'Castle Island (Fort William) commands the main channel. Fort Hill covers from the south.',
      notes: 'Multiple channels between harbor islands require piloting. Long Wharf berths 50 vessels. Frequent fog in spring/summer.',
    },
    terrain: 'Harbor islands, rocky coast. Charles River and Mystic River. Cold winters — very different from Caribbean. Boston Neck is the only land approach.',
    portType: 'major_port',
  },

  willemstad: {
    id: 'willemstad',
    name: 'Willemstad',
    seaZoneId: 'spanish_main_coast',
    controller: 'dutch',
    corruption: 50,
    prosperity: 75,
    population: 3500,
    fortStrength: 50,
    diseaseProfile: { malaria: 20, yellowFever: 15, scurvy: 5, dysentery: 10 },
    tavernQuality: 65,
    shipyardQuality: 60,
    marketSize: 80,
    pirateFriendly: false,
    latitude: 12.11,
    longitude: -68.93,
    description: 'Dutch trade nexus — they trade with EVERYONE regardless of nationality or legality. Money has no flag.',
    harbor: {
      entranceWidth: undefined,
      entranceDepth: 10,
      maxDraft: 8,
      tidalRange: 0.3,
      anchorageCapacity: 60,
      approachDirections: ['south'],
      defenses: 'Fort Amsterdam overlooks the harbor entrance. Waterfort and Rif Fort provide additional coverage.',
      notes: 'Sint Anna Bay — narrow natural channel leading to Schottegat, a large sheltered inner harbor. Deep water.',
    },
    terrain: 'Arid island. Punda (commercial heart) and Otrobanda districts on either side of Sint Anna Bay.',
    portType: 'major_port',
  },

  veracruz: {
    id: 'veracruz',
    name: 'Veracruz',
    seaZoneId: 'gulf_of_mexico',
    controller: 'spain',
    corruption: 40,
    prosperity: 80,
    population: 5500,
    fortStrength: 90,
    diseaseProfile: { malaria: 45, yellowFever: 55, scurvy: 5, dysentery: 25 },
    tavernQuality: 55,
    shipyardQuality: 50,
    marketSize: 75,
    pirateFriendly: false,
    latitude: 19.20,
    longitude: -96.13,
    description: 'Origin port for the New Spain treasure fleet. San Juan de Ulúa is the most heavily armed single fortification in the Spanish Empire.',
    harbor: {
      entranceWidth: undefined,
      entranceDepth: 8,
      maxDraft: 6,
      tidalRange: 0.3,
      anchorageCapacity: 50,
      approachDirections: ['east'],
      defenses: 'Fortaleza de San Juan de Ulúa — island fortress with 250 cannons and 3-foot thick walls rising from the water.',
      notes: 'Open roadstead protected by fortress on island. Ships anchor between fortress and city.',
    },
    terrain: 'Hot, humid coastal lowlands. "The gateway to hell" for newly arrived Spaniards. Yellow fever endemic.',
    portType: 'major_port',
  },

  petit_goave: {
    id: 'petit_goave',
    name: 'Petit-Goâve',
    seaZoneId: 'jamaica_channel',
    controller: 'france',
    corruption: 80,
    prosperity: 40,
    population: 1500,
    fortStrength: 25,
    diseaseProfile: { malaria: 40, yellowFever: 30, scurvy: 10, dysentery: 25 },
    tavernQuality: 70,
    shipyardQuality: 45,
    marketSize: 35,
    pirateFriendly: true,
    latitude: 18.43,
    longitude: -72.87,
    description: 'Replaced Tortuga as the primary French corsair base. Governors actively support corsair operations.',
    harbor: {
      entranceWidth: undefined,
      entranceDepth: 6,
      maxDraft: 5,
      tidalRange: 0.3,
      anchorageCapacity: 30,
      approachDirections: ['south', 'southwest'],
      defenses: 'Small French fort and harbor entrance battery. Modest but functional.',
      notes: 'Sheltered bay protected by islets. Îlet du Carénage specifically used for careening ships.',
    },
    terrain: 'Protected bay with careening island. Close to Spanish Main — ideal launching point for raids.',
    portType: 'minor_port',
  },

  basseterre: {
    id: 'basseterre',
    name: 'Basseterre',
    seaZoneId: 'leeward_islands_waters',
    controller: 'england',
    corruption: 30,
    prosperity: 60,
    population: 2500,
    fortStrength: 60,
    diseaseProfile: { malaria: 25, yellowFever: 20, scurvy: 5, dysentery: 15 },
    tavernQuality: 50,
    shipyardQuality: 40,
    marketSize: 50,
    pirateFriendly: false,
    latitude: 17.30,
    longitude: -62.72,
    description: 'Freshly English from the 1713 Treaty of Utrecht. Sugar island with the "Gibraltar of the West Indies" — Brimstone Hill Fortress.',
    harbor: {
      entranceWidth: undefined,
      entranceDepth: 8,
      maxDraft: 6,
      tidalRange: 0.3,
      anchorageCapacity: 30,
      approachDirections: ['southwest', 'west'],
      defenses: 'Brimstone Hill Fortress dominates the island from 800-foot volcanic hill. Fort Charles and Fort Thomas on the coast.',
      notes: 'Open roadstead — ships anchor offshore and lighter cargo. No natural harbor.',
    },
    terrain: 'Volcanic island almost entirely devoted to sugar production. French population remains from pre-1713 partition.',
    portType: 'minor_port',
  },
};

// ============================================================
// European Background Cities (not full ports — decision centers)
// ============================================================

export const EUROPEAN_CITIES: Record<string, PortProfile> = {
  london: {
    id: 'london',
    name: 'London',
    seaZoneId: 'atlantic_approach',
    controller: 'england',
    corruption: 30,
    prosperity: 95,
    population: 600000,
    fortStrength: 90,
    diseaseProfile: { malaria: 5, yellowFever: 0, scurvy: 5, dysentery: 10 },
    tavernQuality: 80,
    shipyardQuality: 85,
    marketSize: 100,
    pirateFriendly: false,
    latitude: 51.51,
    longitude: -0.13,
    description: 'Seat of the Admiralty, Lloyd\'s Coffee House, Execution Dock. Where anti-piracy policy is made.',
    harbor: {
      tidalRange: 6.5,
      anchorageCapacity: 500,
      approachDirections: ['east'],
      defenses: 'Tower of London, Thames forts. Full Royal Navy presence.',
    },
    terrain: 'Thames estuary. Execution Dock at Wapping where pirates are hanged at low tide.',
    portType: 'european_city',
  },

  seville_cadiz: {
    id: 'seville_cadiz',
    name: 'Seville / Cádiz',
    seaZoneId: 'atlantic_approach',
    controller: 'spain',
    corruption: 35,
    prosperity: 90,
    population: 80000,
    fortStrength: 80,
    diseaseProfile: { malaria: 5, yellowFever: 0, scurvy: 5, dysentery: 5 },
    tavernQuality: 75,
    shipyardQuality: 80,
    marketSize: 95,
    pirateFriendly: false,
    latitude: 37.39,
    longitude: -5.99,
    description: 'Casa de Contratación — controls ALL Spanish colonial commerce. Treasure fleet terminus. Moving from Seville to Cádiz in 1717.',
    harbor: {
      tidalRange: 3.0,
      anchorageCapacity: 200,
      approachDirections: ['west', 'southwest'],
      defenses: 'Multiple coastal forts. Spanish naval base.',
      notes: 'Guadalquivir River silting up — large ships can\'t reach Seville, hence the move to Cádiz.',
    },
    terrain: 'Guadalquivir River. Torre del Oro where treasure cargoes are inspected. Cádiz harbor taking over as deep-water terminus.',
    portType: 'european_city',
  },

  amsterdam: {
    id: 'amsterdam',
    name: 'Amsterdam',
    seaZoneId: 'atlantic_approach',
    controller: 'dutch',
    corruption: 25,
    prosperity: 95,
    population: 200000,
    fortStrength: 70,
    diseaseProfile: { malaria: 0, yellowFever: 0, scurvy: 5, dysentery: 5 },
    tavernQuality: 80,
    shipyardQuality: 90,
    marketSize: 100,
    pirateFriendly: false,
    latitude: 52.37,
    longitude: 4.90,
    description: 'Financial center of Europe. Dutch West India Company HQ. World\'s first stock exchange. Most sophisticated banking system in the world.',
    harbor: {
      tidalRange: 1.5,
      anchorageCapacity: 300,
      approachDirections: ['north'],
      defenses: 'Admiralty of Amsterdam. Dutch naval forces.',
    },
    terrain: 'Canal city. Herengracht warehouses. West India House on Herengracht.',
    portType: 'european_city',
  },
};

// ============================================================
// West African Trading Posts
// ============================================================

export const AFRICAN_POSTS: Record<string, PortProfile> = {
  cape_coast_castle: {
    id: 'cape_coast_castle',
    name: 'Cape Coast Castle',
    seaZoneId: 'west_african_coast',
    controller: 'england',
    corruption: 60,
    prosperity: 50,
    population: 2200,
    fortStrength: 65,
    diseaseProfile: { malaria: 70, yellowFever: 60, scurvy: 5, dysentery: 40 },
    tavernQuality: 30,
    shipyardQuality: 20,
    marketSize: 60,
    pirateFriendly: false,
    latitude: 5.10,
    longitude: -1.24,
    description: 'Royal African Company HQ. Primary English slave trading headquarters in West Africa. The Door of No Return.',
    harbor: {
      tidalRange: 1.0,
      anchorageCapacity: 20,
      approachDirections: ['south'],
      defenses: 'Castle gun batteries facing sea. No natural harbor — open roadstead, ships anchor offshore, cargo lightered by canoes.',
    },
    terrain: 'Open coast. Local African town for fishing, agriculture, trade. Interior trade routes bring enslaved people from inland.',
    portType: 'trading_post',
  },

  elmina: {
    id: 'elmina',
    name: 'Elmina',
    seaZoneId: 'west_african_coast',
    controller: 'dutch',
    corruption: 50,
    prosperity: 55,
    population: 1500,
    fortStrength: 70,
    diseaseProfile: { malaria: 70, yellowFever: 60, scurvy: 5, dysentery: 40 },
    tavernQuality: 25,
    shipyardQuality: 15,
    marketSize: 55,
    pirateFriendly: false,
    latitude: 5.08,
    longitude: -1.35,
    description: 'Oldest European building in sub-Saharan Africa. Built 1482 by Portugal, seized by Dutch 1637. Pragmatic, profit-focused.',
    harbor: {
      tidalRange: 1.0,
      anchorageCapacity: 15,
      approachDirections: ['south'],
      defenses: 'Elmina Castle plus Fort Coenraadsburg on the hilltop overlooking it. The Dutch built the hilltop fort to ensure they could bombard the castle if it was ever retaken.',
    },
    terrain: 'Small bay, better shelter than Cape Coast. Local town surrounds the castle.',
    portType: 'trading_post',
  },

  whydah: {
    id: 'whydah',
    name: 'Whydah',
    seaZoneId: 'west_african_coast',
    controller: 'dahomey',
    corruption: 40,
    prosperity: 60,
    population: 5000,
    fortStrength: 40,
    diseaseProfile: { malaria: 65, yellowFever: 55, scurvy: 5, dysentery: 35 },
    tavernQuality: 20,
    shipyardQuality: 10,
    marketSize: 70,
    pirateFriendly: false,
    latitude: 6.36,
    longitude: 2.08,
    description: 'One of the largest slave trading ports in West Africa. African sovereign territory — European posts exist only with the King of Dahomey\'s permission.',
    harbor: {
      tidalRange: 1.0,
      anchorageCapacity: 15,
      approachDirections: ['south'],
      defenses: 'French, English, and Portuguese trading posts. Dahomey Royal Compound oversees ALL trade. The King sets the price.',
    },
    terrain: 'Open beach. The Route of Slaves — 4km path from town to beach lined with ritual sites. Canoes ferry enslaved people through the surf.',
    portType: 'trading_post',
  },
};

// Combined lookup for all ports
export const ALL_PORTS: Record<string, PortProfile> = {
  ...PORT_PROFILES,
  ...EUROPEAN_CITIES,
  ...AFRICAN_POSTS,
};
