import { z } from 'zod';

// ============================================================
// Sea Zone definitions — the ocean as playable space
// Replaces the old region system with 25 named sea zones
// ============================================================

const SeaZoneDefSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  zoneType: z.enum(['shallow_coastal', 'deep_channel', 'narrow_strait', 'open_ocean', 'coastal_approaches', 'island_waters', 'submerged_reef', 'continental_shelf', 'semi_enclosed_sea', 'tropical_coastal']),
  trafficDensity: z.enum(['very_low', 'low', 'moderate', 'high', 'very_high']),
  patrolLevel: z.enum(['none', 'low', 'moderate', 'high', 'very_high']),
  hazards: z.array(z.string()),
  currentDirection: z.string(),
  currentSpeed: z.number(),         // knots
  windPattern: z.string(),
  encounterChance: z.number(),      // 0-100 percentage per tick
  adjacentZones: z.array(z.string()),
  accessiblePorts: z.array(z.string()),
  pirateValue: z.string(),
  namedFeatures: z.array(z.string()).optional(),
  hurricaneSeason: z.boolean(),
});

export type SeaZoneDefinition = z.infer<typeof SeaZoneDefSchema>;

export const SEA_ZONE_DEFINITIONS: Record<string, SeaZoneDefinition> = {
  great_bahama_bank: {
    id: 'great_bahama_bank',
    name: 'Great Bahama Bank',
    description: 'Extremely shallow waters (3-30 feet). Pirate sloops navigate here; navy warships cannot follow.',
    zoneType: 'shallow_coastal',
    trafficDensity: 'moderate',
    patrolLevel: 'low',
    hazards: ['coral_heads', 'shifting_sandbars', 'unmarked_channels'],
    currentDirection: 'west',
    currentSpeed: 0.3,
    windPattern: 'Steady trade winds, less sheltered than among the islands.',
    encounterChance: 12,
    adjacentZones: ['providence_channel', 'old_bahama_channel', 'bahama_channel'],
    accessiblePorts: ['nassau'],
    pirateValue: 'Safe haven — shallow-draft pirate sloops can navigate here, deep-draft navy warships cannot follow.',
    namedFeatures: ['Hog Island', 'Eleuthera', 'Andros Island'],
    hurricaneSeason: true,
  },

  providence_channel: {
    id: 'providence_channel',
    name: 'Providence Channel',
    description: 'Deep water channel between Bahama islands. The front door to Nassau.',
    zoneType: 'deep_channel',
    trafficDensity: 'high',
    patrolLevel: 'moderate',
    hazards: ['reef_edges', 'strong_currents'],
    currentDirection: 'west',
    currentSpeed: 0.5,
    windPattern: 'Trade winds funneled through island gaps.',
    encounterChance: 15,
    adjacentZones: ['great_bahama_bank', 'atlantic_approach', 'bahama_channel', 'turks_passage'],
    accessiblePorts: [],
    pirateValue: 'Nassau\'s front door — anyone approaching from the Atlantic comes through here.',
    namedFeatures: ['New Providence Island'],
    hurricaneSeason: true,
  },

  florida_straits: {
    id: 'florida_straits',
    name: 'Florida Straits',
    description: 'Narrow deep-water passage. THE chokepoint — every treasure fleet passes through here.',
    zoneType: 'narrow_strait',
    trafficDensity: 'very_high',
    patrolLevel: 'high',
    hazards: ['gulf_stream_current', 'florida_reefs', 'cuban_shoals'],
    currentDirection: 'north',
    currentSpeed: 3.5,
    windPattern: 'Variable — trade winds from east, Gulf breezes from west.',
    encounterChance: 20,
    adjacentZones: ['havana_roads', 'great_bahama_bank', 'bahama_channel', 'gulf_of_mexico'],
    accessiblePorts: [],
    pirateValue: 'PRIME — treasure fleet route. 1715 Wreck Sites on the Florida reef side.',
    namedFeatures: ['Florida Reef', '1715 Wreck Sites'],
    hurricaneSeason: true,
  },

  havana_roads: {
    id: 'havana_roads',
    name: 'Havana Roads',
    description: 'Coastal waters approaching Havana. Treasure fleet assembly area.',
    zoneType: 'coastal_approaches',
    trafficDensity: 'very_high',
    patrolLevel: 'very_high',
    hazards: ['fortress_guns', 'harbor_chain'],
    currentDirection: 'north',
    currentSpeed: 1.0,
    windPattern: 'Land/sea breeze cycle, trade winds.',
    encounterChance: 18,
    adjacentZones: ['florida_straits', 'old_bahama_channel', 'yucatan_channel', 'caribbean_deep_basin'],
    accessiblePorts: ['havana'],
    pirateValue: 'High risk, high reward — approaching means sailing under fortress guns.',
    namedFeatures: ['Morro Castle', 'Harbor Chain'],
    hurricaneSeason: true,
  },

  old_bahama_channel: {
    id: 'old_bahama_channel',
    name: 'Old Bahama Channel',
    description: 'Narrow channel between Cuba and the Bahamas. Back route for smugglers avoiding Florida Straits.',
    zoneType: 'deep_channel',
    trafficDensity: 'moderate',
    patrolLevel: 'low',
    hazards: ['shoals', 'reefs', 'confined_waters'],
    currentDirection: 'northwest',
    currentSpeed: 0.5,
    windPattern: 'Trade winds, somewhat sheltered by Cuba.',
    encounterChance: 10,
    adjacentZones: ['great_bahama_bank', 'havana_roads', 'windward_passage'],
    accessiblePorts: [],
    pirateValue: 'Back route used by smugglers and pirates avoiding heavily-patrolled Florida Straits.',
    namedFeatures: ['Cayo Coco', 'Cayo Romano'],
    hurricaneSeason: true,
  },

  windward_passage: {
    id: 'windward_passage',
    name: 'Windward Passage',
    description: 'Major strait between Cuba and Hispaniola. THE strategic chokepoint of the Caribbean.',
    zoneType: 'narrow_strait',
    trafficDensity: 'high',
    patrolLevel: 'high',
    hazards: ['funneled_winds', 'strong_currents', 'confused_seas'],
    currentDirection: 'west',
    currentSpeed: 1.5,
    windPattern: 'Trade winds compressed between Cuba and Hispaniola — can be fierce.',
    encounterChance: 18,
    adjacentZones: ['old_bahama_channel', 'jamaica_channel', 'tortuga_waters', 'silver_bank'],
    accessiblePorts: [],
    pirateValue: 'PRIME — whoever controls the Windward Passage controls traffic flow.',
    namedFeatures: ['Cape Tiburon', 'Point Maisi'],
    hurricaneSeason: true,
  },

  jamaica_channel: {
    id: 'jamaica_channel',
    name: 'Jamaica Channel',
    description: 'Open deep water between Jamaica, Cuba, and Hispaniola. English-controlled waters.',
    zoneType: 'open_ocean',
    trafficDensity: 'high',
    patrolLevel: 'high',
    hazards: ['pedro_bank'],
    currentDirection: 'west',
    currentSpeed: 0.5,
    windPattern: 'Steady trade winds.',
    encounterChance: 15,
    adjacentZones: ['windward_passage', 'kingston_approaches', 'cayman_trench', 'caribbean_deep_basin'],
    accessiblePorts: ['petit_goave'],
    pirateValue: 'Good — English trade routes. Jamaica Squadron patrols actively.',
    namedFeatures: ['Pedro Bank'],
    hurricaneSeason: true,
  },

  kingston_approaches: {
    id: 'kingston_approaches',
    name: 'Kingston Approaches',
    description: 'Waters immediately around Port Royal/Kingston. Major naval and commercial port.',
    zoneType: 'coastal_approaches',
    trafficDensity: 'very_high',
    patrolLevel: 'very_high',
    hazards: ['palisadoes_sandbar', 'harbor_piloting'],
    currentDirection: 'west',
    currentSpeed: 0.3,
    windPattern: 'Land/sea breeze cycle.',
    encounterChance: 15,
    adjacentZones: ['jamaica_channel', 'cayman_trench'],
    accessiblePorts: ['port_royal'],
    pirateValue: 'Low — approaching means passing Navy warships at anchor.',
    namedFeatures: ['Palisadoes Sandbar', 'Fort Charles'],
    hurricaneSeason: true,
  },

  cayman_trench: {
    id: 'cayman_trench',
    name: 'Cayman Trench',
    description: 'Deepest part of the Caribbean (25,000+ feet). Quiet waters, good for hiding.',
    zoneType: 'open_ocean',
    trafficDensity: 'low',
    patrolLevel: 'low',
    hazards: ['remoteness'],
    currentDirection: 'west',
    currentSpeed: 0.5,
    windPattern: 'Steady trade winds.',
    encounterChance: 8,
    adjacentZones: ['jamaica_channel', 'kingston_approaches', 'yucatan_channel', 'caribbean_deep_basin'],
    accessiblePorts: [],
    pirateValue: 'Quiet hiding. Cayman Islands accessible — turtle hunting, fresh water, careening.',
    namedFeatures: ['Grand Cayman'],
    hurricaneSeason: true,
  },

  caribbean_deep_basin: {
    id: 'caribbean_deep_basin',
    name: 'Caribbean Deep Basin',
    description: 'Central Caribbean open ocean. Days from any port. The open crossing.',
    zoneType: 'open_ocean',
    trafficDensity: 'moderate',
    patrolLevel: 'low',
    hazards: ['isolation', 'becalming', 'no_shelter_from_storms'],
    currentDirection: 'west',
    currentSpeed: 0.5,
    windPattern: 'Steady trade winds, reliable but exposed.',
    encounterChance: 10,
    adjacentZones: ['jamaica_channel', 'havana_roads', 'spanish_main_coast', 'windward_islands_waters', 'leeward_islands_waters', 'cayman_trench', 'darien_coast'],
    accessiblePorts: [],
    pirateValue: 'Open crossing — low encounter chance but no witnesses either.',
    namedFeatures: ['Open Caribbean Crossing'],
    hurricaneSeason: true,
  },

  tortuga_waters: {
    id: 'tortuga_waters',
    name: 'Tortuga Waters',
    description: 'North coast of Hispaniola. Historically the original pirate waters.',
    zoneType: 'island_waters',
    trafficDensity: 'low',
    patrolLevel: 'low',
    hazards: ['reefs_around_tortuga', 'coastal_currents'],
    currentDirection: 'northwest',
    currentSpeed: 0.5,
    windPattern: 'Trade winds, somewhat sheltered by Hispaniola\'s mountains.',
    encounterChance: 12,
    adjacentZones: ['windward_passage', 'silver_bank', 'mona_passage'],
    accessiblePorts: ['tortuga', 'santo_domingo'],
    pirateValue: 'Original pirate waters. Now quieter but corsair activity continues. Many hidden coves.',
    namedFeatures: ['Tortuga Island', 'North Hispaniola Coves'],
    hurricaneSeason: true,
  },

  silver_bank: {
    id: 'silver_bank',
    name: 'Silver Bank',
    description: 'Submerged reef north of Hispaniola. Graveyard of ships. Treasure wrecks and whale breeding ground.',
    zoneType: 'submerged_reef',
    trafficDensity: 'very_low',
    patrolLevel: 'none',
    hazards: ['extreme_reefs', 'barely_submerged', 'hundreds_of_wrecks'],
    currentDirection: 'northwest',
    currentSpeed: 0.5,
    windPattern: 'Trade winds, exposed.',
    encounterChance: 1,
    adjacentZones: ['tortuga_waters', 'mona_passage', 'turks_passage', 'atlantic_approach'],
    accessiblePorts: [],
    pirateValue: 'Salvage only. Treasure wrecks for the daring. Humpback whale breeding ground in winter.',
    namedFeatures: ['Spanish Treasure Wrecks', 'Whale Breeding Ground'],
    hurricaneSeason: true,
  },

  mona_passage: {
    id: 'mona_passage',
    name: 'Mona Passage',
    description: 'Major strait between Hispaniola and Puerto Rico. Less patrolled than Windward Passage but more dangerous.',
    zoneType: 'narrow_strait',
    trafficDensity: 'moderate',
    patrolLevel: 'moderate',
    hazards: ['strong_currents', 'reefs_around_mona_island', 'confused_seas'],
    currentDirection: 'west',
    currentSpeed: 1.0,
    windPattern: 'Accelerated trade winds through the gap.',
    encounterChance: 12,
    adjacentZones: ['tortuga_waters', 'silver_bank', 'anegada_passage', 'leeward_islands_waters'],
    accessiblePorts: [],
    pirateValue: 'Less patrolled alternative to Windward Passage.',
    namedFeatures: ['Mona Island', 'Desecheo Island'],
    hurricaneSeason: true,
  },

  anegada_passage: {
    id: 'anegada_passage',
    name: 'Anegada Passage',
    description: 'Between Virgin Islands and open Atlantic. Gateway into the Caribbean from Europe/Africa.',
    zoneType: 'narrow_strait',
    trafficDensity: 'moderate',
    patrolLevel: 'moderate',
    hazards: ['anegada_island_invisible_flat', 'extensive_reefs'],
    currentDirection: 'west',
    currentSpeed: 0.5,
    windPattern: 'Trade winds, can be strong.',
    encounterChance: 7,
    adjacentZones: ['mona_passage', 'leeward_islands_waters', 'atlantic_approach'],
    accessiblePorts: [],
    pirateValue: 'Moderate — first landfall after weeks at sea. Ships arriving from Europe enter here.',
    namedFeatures: ['Anegada Island'],
    hurricaneSeason: true,
  },

  leeward_islands_waters: {
    id: 'leeward_islands_waters',
    name: 'Leeward Islands Waters',
    description: 'Northern Lesser Antilles. Many small islands, multiple colonial powers, mixed jurisdictions.',
    zoneType: 'island_waters',
    trafficDensity: 'moderate',
    patrolLevel: 'moderate',
    hazards: ['volcanic_drop_offs', 'channel_currents', 'wind_shadows'],
    currentDirection: 'west',
    currentSpeed: 0.5,
    windPattern: 'Trade winds with island effects — wind shadows behind islands, acceleration between them.',
    encounterChance: 12,
    adjacentZones: ['anegada_passage', 'mona_passage', 'windward_islands_waters', 'caribbean_deep_basin'],
    accessiblePorts: ['basseterre'],
    pirateValue: 'Good — many small harbors and hidden coves. Play one nation against another.',
    namedFeatures: ['St. Kitts', 'Nevis', 'Antigua'],
    hurricaneSeason: true,
  },

  windward_islands_waters: {
    id: 'windward_islands_waters',
    name: 'Windward Islands Waters',
    description: 'Southern Lesser Antilles. Sugar trade heartland. Bridgetown is the first Caribbean port from the Atlantic.',
    zoneType: 'island_waters',
    trafficDensity: 'high',
    patrolLevel: 'moderate',
    hazards: ['volcanic_islands', 'channel_currents', 'hurricane_first_strike'],
    currentDirection: 'west',
    currentSpeed: 0.5,
    windPattern: 'Strong trade winds — constant blow. Called "Windward" for a reason.',
    encounterChance: 14,
    adjacentZones: ['leeward_islands_waters', 'caribbean_deep_basin', 'tobago_channel', 'atlantic_approach'],
    accessiblePorts: ['bridgetown'],
    pirateValue: 'Good — sugar trade. Ships arriving from Europe/Africa hit Barbados first.',
    namedFeatures: ['Barbados', 'Martinique', 'St. Lucia'],
    hurricaneSeason: true,
  },

  spanish_main_coast: {
    id: 'spanish_main_coast',
    name: 'Spanish Main Coast',
    description: 'Northern South American coast. The richest coast in the Americas — Cartagena is here.',
    zoneType: 'tropical_coastal',
    trafficDensity: 'high',
    patrolLevel: 'high',
    hazards: ['river_sediment', 'coastal_shallows', 'afternoon_thunderstorms', 'guarda_costa'],
    currentDirection: 'west',
    currentSpeed: 0.5,
    windPattern: 'Morning calm, afternoon sea breeze, evening land breeze. Afternoon thunderstorms almost daily.',
    encounterChance: 15,
    adjacentZones: ['caribbean_deep_basin', 'windward_islands_waters', 'darien_coast', 'tobago_channel'],
    accessiblePorts: ['cartagena', 'willemstad'],
    pirateValue: 'Rich prizes, heavy patrol. Guarda Costa can seize ANY non-Spanish vessel.',
    namedFeatures: ['Boca Chica', 'Islas del Rosario'],
    hurricaneSeason: false, // partially protected by South American landmass
  },

  darien_coast: {
    id: 'darien_coast',
    name: 'Darién Coast',
    description: 'Panama/Colombia coast. Portobelo and the treasure fair terminus.',
    zoneType: 'tropical_coastal',
    trafficDensity: 'moderate',
    patrolLevel: 'moderate',
    hazards: ['jungle_coast', 'river_mouths', 'disease_swamps'],
    currentDirection: 'west',
    currentSpeed: 0.3,
    windPattern: 'Variable, sheltered by Central American landmass.',
    encounterChance: 12,
    adjacentZones: ['spanish_main_coast', 'cayman_trench', 'caribbean_deep_basin'],
    accessiblePorts: ['portobelo'],
    pirateValue: 'Moderate — treasure fair makes these waters packed during fair season, quiet between fairs.',
    namedFeatures: ['Fort San Lorenzo', 'Chagres River Mouth'],
    hurricaneSeason: true,
  },

  gulf_of_mexico: {
    id: 'gulf_of_mexico',
    name: 'Gulf of Mexico',
    description: 'Large semi-enclosed sea. Veracruz trade, New Spain treasure fleet origin.',
    zoneType: 'semi_enclosed_sea',
    trafficDensity: 'moderate',
    patrolLevel: 'moderate',
    hazards: ['northers', 'hurricane_path', 'shallow_coastal_waters'],
    currentDirection: 'clockwise_loop',
    currentSpeed: 0.5,
    windPattern: 'Variable — trade winds weaker here, northers dominate winter.',
    encounterChance: 5,
    adjacentZones: ['florida_straits', 'yucatan_channel', 'havana_roads'],
    accessiblePorts: ['veracruz'],
    pirateValue: 'Moderate — less pirate activity than Caribbean proper but Veracruz treasure fleet originates here.',
    namedFeatures: ['San Juan de Ulua'],
    hurricaneSeason: true,
  },

  yucatan_channel: {
    id: 'yucatan_channel',
    name: 'Yucatan Channel',
    description: 'Wide deep strait between Cuba and Mexico. Connects Gulf of Mexico to Caribbean.',
    zoneType: 'narrow_strait',
    trafficDensity: 'moderate',
    patrolLevel: 'low',
    hazards: ['strong_currents', 'loop_current'],
    currentDirection: 'northwest',
    currentSpeed: 1.0,
    windPattern: 'Trade winds, somewhat variable near the Yucatan coast.',
    encounterChance: 5,
    adjacentZones: ['gulf_of_mexico', 'havana_roads', 'cayman_trench'],
    accessiblePorts: [],
    pirateValue: 'Moderate — ships from Veracruz to Havana pass through.',
    namedFeatures: ['Yucatan Peninsula', 'Cape Catoche'],
    hurricaneSeason: true,
  },

  bahama_channel: {
    id: 'bahama_channel',
    name: 'Bahama Channel',
    description: 'Open water channel between Bahamas and the American coast. Gulf Stream highway.',
    zoneType: 'deep_channel',
    trafficDensity: 'high',
    patrolLevel: 'low',
    hazards: ['gulf_stream', 'bahama_banks_east_side'],
    currentDirection: 'north',
    currentSpeed: 2.5,
    windPattern: 'Trade winds plus coastal effects.',
    encounterChance: 7,
    adjacentZones: ['great_bahama_bank', 'providence_channel', 'carolina_shelf', 'florida_straits'],
    accessiblePorts: [],
    pirateValue: 'Moderate — route from Caribbean to American colonies. Gulf Stream makes northbound travel fast.',
    namedFeatures: ['Gulf Stream'],
    hurricaneSeason: true,
  },

  carolina_shelf: {
    id: 'carolina_shelf',
    name: 'Carolina Shelf',
    description: 'Coastal waters off the Carolinas. Blackbeard\'s hunting ground.',
    zoneType: 'continental_shelf',
    trafficDensity: 'moderate',
    patrolLevel: 'low',
    hazards: ['shoals', 'cape_hatteras', 'barrier_islands', 'inlets'],
    currentDirection: 'north',
    currentSpeed: 1.0,
    windPattern: 'Variable — trade winds fade at this latitude, northers in winter.',
    encounterChance: 7,
    adjacentZones: ['bahama_channel', 'boston_waters'],
    accessiblePorts: ['charles_town'],
    pirateValue: 'Good — low patrol. Outer Banks provide shelter and ambush points.',
    namedFeatures: ['Cape Hatteras', 'Cape Fear', 'Ocracoke Inlet'],
    hurricaneSeason: false,
  },

  boston_waters: {
    id: 'boston_waters',
    name: 'Boston Waters',
    description: 'New England cold coastal waters. Rich shipping but pirates face hostile reception.',
    zoneType: 'continental_shelf',
    trafficDensity: 'high',
    patrolLevel: 'moderate',
    hazards: ['rocky_coast', 'fog', 'winter_storms', 'ice'],
    currentDirection: 'south',
    currentSpeed: 0.5,
    windPattern: 'Westerlies dominate, nor\'easters in winter, sea fog in spring/summer.',
    encounterChance: 7,
    adjacentZones: ['carolina_shelf', 'atlantic_approach'],
    accessiblePorts: ['boston'],
    pirateValue: 'Rich shipping, fewer patrols than Caribbean. But Boston hangs pirates.',
    namedFeatures: ['Boston Harbor', 'Cape Cod'],
    hurricaneSeason: false,
  },

  atlantic_approach: {
    id: 'atlantic_approach',
    name: 'Atlantic Approach',
    description: 'Mid-Atlantic open ocean. Vast emptiness. Crossing takes 4-12 weeks.',
    zoneType: 'open_ocean',
    trafficDensity: 'very_low',
    patrolLevel: 'none',
    hazards: ['storms', 'isolation', 'becalming', 'weeks_from_land'],
    currentDirection: 'west',
    currentSpeed: 0.5,
    windPattern: 'Trade winds (low latitudes), westerlies (high latitudes), doldrums near equator.',
    encounterChance: 1,
    adjacentZones: ['boston_waters', 'carolina_shelf', 'providence_channel', 'anegada_passage', 'windward_islands_waters', 'silver_bank', 'west_african_coast', 'tobago_channel'],
    accessiblePorts: [],
    pirateValue: 'Transatlantic intercept — no witnesses, no rescue, no escape.',
    namedFeatures: ['Sargasso Sea', 'Horse Latitudes'],
    hurricaneSeason: false,
  },

  turks_passage: {
    id: 'turks_passage',
    name: 'Turks Passage',
    description: 'Between Bahamas and Hispaniola. Less-used passage, good for avoiding patrolled routes.',
    zoneType: 'narrow_strait',
    trafficDensity: 'low',
    patrolLevel: 'low',
    hazards: ['turks_and_caicos_reefs'],
    currentDirection: 'west',
    currentSpeed: 0.5,
    windPattern: 'Trade winds.',
    encounterChance: 3,
    adjacentZones: ['great_bahama_bank', 'silver_bank', 'providence_channel'],
    accessiblePorts: [],
    pirateValue: 'Low traffic but good for evasion. Turks and Caicos cays offer hideouts.',
    namedFeatures: ['Turks Islands', 'Caicos Bank'],
    hurricaneSeason: true,
  },

  tobago_channel: {
    id: 'tobago_channel',
    name: 'Tobago Channel',
    description: 'Southern gateway into the Caribbean between Lesser Antilles and South America.',
    zoneType: 'narrow_strait',
    trafficDensity: 'moderate',
    patrolLevel: 'low',
    hazards: ['strong_currents', 'atlantic_meets_caribbean'],
    currentDirection: 'west',
    currentSpeed: 1.5,
    windPattern: 'Strong trade winds.',
    encounterChance: 5,
    adjacentZones: ['windward_islands_waters', 'spanish_main_coast', 'atlantic_approach'],
    accessiblePorts: [],
    pirateValue: 'Moderate — ships from Africa or southern Atlantic enter here.',
    namedFeatures: ['Tobago', 'Trinidad'],
    hurricaneSeason: true,
  },

  west_african_coast: {
    id: 'west_african_coast',
    name: 'West African Coast',
    description: 'Tropical coastal waters. The other end of the triangle trade. Bartholomew Roberts operated here.',
    zoneType: 'tropical_coastal',
    trafficDensity: 'moderate',
    patrolLevel: 'moderate',
    hazards: ['sandbars', 'strong_coastal_currents', 'extreme_disease'],
    currentDirection: 'east',
    currentSpeed: 0.5,
    windPattern: 'Variable — monsoon patterns, harmattan, calms.',
    encounterChance: 5,
    adjacentZones: ['atlantic_approach'],
    accessiblePorts: ['cape_coast_castle', 'elmina', 'whydah'],
    pirateValue: 'Moderate — slave ships are rich targets. European forts along the Gold Coast.',
    namedFeatures: ['Cape Coast Castle', 'Elmina Castle', 'Gold Coast'],
    hurricaneSeason: false,
  },
};

// Legacy compatibility — distance between sea zones (for route calculations)
// These are approximate transit distances in nautical miles between adjacent zones
export const SEA_ZONE_TRANSIT_DISTANCES: Record<string, Record<string, number>> = {
  great_bahama_bank:     { providence_channel: 80, old_bahama_channel: 100, bahama_channel: 100 },
  providence_channel:    { great_bahama_bank: 80, atlantic_approach: 400, bahama_channel: 120, turks_passage: 200 },
  florida_straits:       { havana_roads: 60, great_bahama_bank: 150, bahama_channel: 150, gulf_of_mexico: 200 },
  havana_roads:          { florida_straits: 60, old_bahama_channel: 100, yucatan_channel: 200, caribbean_deep_basin: 300 },
  old_bahama_channel:    { great_bahama_bank: 100, havana_roads: 100, windward_passage: 200 },
  windward_passage:      { old_bahama_channel: 200, jamaica_channel: 150, tortuga_waters: 100, silver_bank: 150 },
  jamaica_channel:       { windward_passage: 150, kingston_approaches: 80, cayman_trench: 200, caribbean_deep_basin: 200 },
  kingston_approaches:   { jamaica_channel: 80, cayman_trench: 150 },
  cayman_trench:         { jamaica_channel: 200, kingston_approaches: 150, yucatan_channel: 250, caribbean_deep_basin: 250 },
  caribbean_deep_basin:  { jamaica_channel: 200, havana_roads: 300, spanish_main_coast: 300, windward_islands_waters: 400, leeward_islands_waters: 350, cayman_trench: 250, darien_coast: 300 },
  tortuga_waters:        { windward_passage: 100, silver_bank: 100, mona_passage: 150 },
  silver_bank:           { tortuga_waters: 100, mona_passage: 100, turks_passage: 150, atlantic_approach: 500 },
  mona_passage:          { tortuga_waters: 150, silver_bank: 100, anegada_passage: 200, leeward_islands_waters: 150 },
  anegada_passage:       { mona_passage: 200, leeward_islands_waters: 100, atlantic_approach: 500 },
  leeward_islands_waters:{ anegada_passage: 100, mona_passage: 150, windward_islands_waters: 150, caribbean_deep_basin: 350 },
  windward_islands_waters:{ leeward_islands_waters: 150, caribbean_deep_basin: 400, tobago_channel: 100, atlantic_approach: 600 },
  spanish_main_coast:    { caribbean_deep_basin: 300, windward_islands_waters: 300, darien_coast: 200, tobago_channel: 250 },
  darien_coast:          { spanish_main_coast: 200, cayman_trench: 300, caribbean_deep_basin: 300 },
  gulf_of_mexico:        { florida_straits: 200, yucatan_channel: 300, havana_roads: 250 },
  yucatan_channel:       { gulf_of_mexico: 300, havana_roads: 200, cayman_trench: 250 },
  bahama_channel:        { great_bahama_bank: 100, providence_channel: 120, carolina_shelf: 300, florida_straits: 150 },
  carolina_shelf:        { bahama_channel: 300, boston_waters: 400 },
  boston_waters:          { carolina_shelf: 400, atlantic_approach: 600 },
  atlantic_approach:     { boston_waters: 600, carolina_shelf: 700, providence_channel: 400, anegada_passage: 500, windward_islands_waters: 600, silver_bank: 500, west_african_coast: 3000, tobago_channel: 700 },
  turks_passage:         { great_bahama_bank: 200, silver_bank: 150, providence_channel: 200 },
  tobago_channel:        { windward_islands_waters: 100, spanish_main_coast: 250, atlantic_approach: 700 },
  west_african_coast:    { atlantic_approach: 3000 },
};

