import { z } from 'zod';

const ShipClassSchema = z.object({
  id: z.string(),
  name: z.string(),
  hull: z.number(),
  speed: z.number(),
  maneuverability: z.number(),
  maxGuns: z.number(),
  crewMin: z.number(),
  crewMax: z.number(),
  cargoCapacity: z.number(),
  cost: z.number(),
  draftDepth: z.number(),    // meters — critical for shallow water / harbor access
  description: z.string(),
});

export type ShipClass = z.infer<typeof ShipClassSchema>;

export const SHIP_CLASSES: Record<string, ShipClass> = {

  // ══════════════════════════════════════════════════════════
  // COASTAL / UTILITY — small, cheap, high turnover
  // ══════════════════════════════════════════════════════════

  periagua: {
    id: 'periagua',
    name: 'Periagua',
    hull: 30,
    speed: 6,
    maneuverability: 9,
    maxGuns: 2,
    crewMin: 4,
    crewMax: 15,
    cargoCapacity: 10,
    cost: 200,
    draftDepth: 0.5,
    description: 'Small dugout canoe with sail. Fast, agile, nearly invisible. Used for raids in shallow waters.',
  },
  shallop: {
    id: 'shallop',
    name: 'Shallop',
    hull: 25,
    speed: 5,
    maneuverability: 8,
    maxGuns: 0,
    crewMin: 2,
    crewMax: 8,
    cargoCapacity: 15,
    cost: 100,
    draftDepth: 0.3,
    description: 'Open or half-decked workboat. Ferries supplies between anchorage and shore, shuttles cargo between nearby ports. Every harbor has several.',
  },
  droger: {
    id: 'droger',
    name: 'Droger',
    hull: 35,
    speed: 5,
    maneuverability: 7,
    maxGuns: 2,
    crewMin: 3,
    crewMax: 12,
    cargoCapacity: 30,
    cost: 400,
    draftDepth: 1.0,
    description: 'Single-masted coaster that shuttles sugar hogsheads and rum barrels between islands. The ant of Caribbean commerce — too small for most pirates to bother with.',
  },

  // ══════════════════════════════════════════════════════════
  // REGIONAL TRADERS — the workhorses
  // ══════════════════════════════════════════════════════════

  sloop: {
    id: 'sloop',
    name: 'Sloop',
    hull: 50,
    speed: 8,
    maneuverability: 8,
    maxGuns: 8,
    crewMin: 15,
    crewMax: 75,
    cargoCapacity: 40,
    cost: 1500,
    draftDepth: 2.0,
    description: 'The Caribbean workhorse. Fast, maneuverable, shallow draft. Equally common as pirate vessel and trading craft.',
  },
  schooner: {
    id: 'schooner',
    name: 'Schooner',
    hull: 55,
    speed: 9,
    maneuverability: 7,
    maxGuns: 12,
    crewMin: 20,
    crewMax: 80,
    cargoCapacity: 50,
    cost: 2500,
    draftDepth: 2.5,
    description: 'Fore-and-aft rigged for speed. Excellent upwind performance. Popular with experienced pirates and fast traders.',
  },
  bark: {
    id: 'bark',
    name: 'Bark',
    hull: 60,
    speed: 6,
    maneuverability: 5,
    maxGuns: 14,
    crewMin: 25,
    crewMax: 80,
    cargoCapacity: 100,
    cost: 4000,
    draftDepth: 3.0,
    description: 'Three-masted trader — square-rigged fore, lateen mizzen. The mid-range bulk carrier of colonial trade. Carries tobacco from Carolina, sugar from Barbados, provisions from Boston.',
  },

  // ══════════════════════════════════════════════════════════
  // COMBAT / DUAL-PURPOSE — pirate and navy vessels
  // ══════════════════════════════════════════════════════════

  galley: {
    id: 'galley',
    name: 'Galley',
    hull: 45,
    speed: 6,
    maneuverability: 7,
    maxGuns: 6,
    crewMin: 40,
    crewMax: 130,
    cargoCapacity: 30,
    cost: 3000,
    draftDepth: 1.5,
    description: 'Oar-powered warship used by Spanish guardacostas to patrol Caribbean coasts. Can move when becalmed — deadly advantage in calm tropical waters. Crew-heavy, low cargo, but shallow draft lets it pursue into rivers and coves.',
  },
  packet_boat: {
    id: 'packet_boat',
    name: 'Packet Boat',
    hull: 40,
    speed: 9,
    maneuverability: 8,
    maxGuns: 6,
    crewMin: 10,
    crewMax: 30,
    cargoCapacity: 20,
    cost: 1800,
    draftDepth: 1.8,
    description: 'Fast dispatch vessel carrying mail, orders, and intelligence between ports. Lightly armed but built for speed above all else. Every colonial navy relies on these for communication.',
  },
  brigantine: {
    id: 'brigantine',
    name: 'Brigantine',
    hull: 65,
    speed: 7,
    maneuverability: 6,
    maxGuns: 16,
    crewMin: 30,
    crewMax: 120,
    cargoCapacity: 80,
    cost: 5000,
    draftDepth: 3.0,
    description: 'Two-masted hybrid rig. Good balance of speed, firepower, and cargo. Pirate flagship material.',
  },
  brig: {
    id: 'brig',
    name: 'Brig',
    hull: 70,
    speed: 6,
    maneuverability: 5,
    maxGuns: 20,
    crewMin: 40,
    crewMax: 150,
    cargoCapacity: 100,
    cost: 8000,
    draftDepth: 3.5,
    description: 'Square-rigged warship. Heavy firepower, decent speed. Used by both pirates and navies.',
  },
  frigate: {
    id: 'frigate',
    name: 'Frigate',
    hull: 85,
    speed: 7,
    maneuverability: 4,
    maxGuns: 36,
    crewMin: 100,
    crewMax: 250,
    cargoCapacity: 120,
    cost: 20000,
    draftDepth: 5.0,
    description: 'Purpose-built warship. Fast for its size, devastating broadside. Navy pirate-hunter.',
  },
  man_of_war: {
    id: 'man_of_war',
    name: 'Man-of-War',
    hull: 100,
    speed: 5,
    maneuverability: 2,
    maxGuns: 60,
    crewMin: 200,
    crewMax: 500,
    cargoCapacity: 150,
    cost: 50000,
    draftDepth: 7.0,
    description: 'The most powerful warship afloat. Only navies and the boldest pirates command these.',
  },

  // ══════════════════════════════════════════════════════════
  // TRANSATLANTIC / HEAVY TRADE — high value, fewer in number
  // ══════════════════════════════════════════════════════════

  fluyt: {
    id: 'fluyt',
    name: 'Fluyt',
    hull: 65,
    speed: 5,
    maneuverability: 3,
    maxGuns: 10,
    crewMin: 15,
    crewMax: 40,
    cargoCapacity: 280,
    cost: 8000,
    draftDepth: 4.5,
    description: 'Dutch masterpiece of efficiency — maximum cargo, minimum crew. The most cost-effective bulk carrier afloat. Nearly defenseless, relies on convoys or Dutch naval escorts.',
  },
  merchantman: {
    id: 'merchantman',
    name: 'Merchantman',
    hull: 70,
    speed: 5,
    maneuverability: 4,
    maxGuns: 20,
    crewMin: 35,
    crewMax: 100,
    cargoCapacity: 200,
    cost: 10000,
    draftDepth: 4.0,
    description: 'Armed Atlantic trader. Carries 12-20 guns for self-defense but not a true warship. The backbone of English and French transatlantic trade.',
  },
  galleon: {
    id: 'galleon',
    name: 'Galleon',
    hull: 90,
    speed: 4,
    maneuverability: 3,
    maxGuns: 30,
    crewMin: 80,
    crewMax: 200,
    cargoCapacity: 250,
    cost: 25000,
    draftDepth: 6.0,
    description: 'Spanish treasure ship. Slow but massive cargo capacity. The ultimate prize.',
  },
  guineaman: {
    id: 'guineaman',
    name: 'Guineaman',
    hull: 55,
    speed: 5,
    maneuverability: 4,
    maxGuns: 16,
    crewMin: 30,
    crewMax: 80,
    cargoCapacity: 150,
    cost: 6000,
    draftDepth: 3.5,
    description: 'Slave trade vessel modified for the Middle Passage. Carries trade goods to Africa, enslaved people to the Caribbean, sugar and rum back to Europe. The triangle trade incarnate.',
  },
  east_indiaman: {
    id: 'east_indiaman',
    name: 'East Indiaman',
    hull: 80,
    speed: 5,
    maneuverability: 3,
    maxGuns: 36,
    crewMin: 100,
    crewMax: 200,
    cargoCapacity: 350,
    cost: 30000,
    draftDepth: 5.5,
    description: 'VOC or EIC vessel carrying spices, silk, and porcelain from Asia. Heavily armed, heavily loaded. Not common in Caribbean waters but passes through — a legendary prize.',
  },
};
